<?php
/**
 * Created by PhpStorm.
 * User: utkir
 * Date: 07.08.2018
 * Time: 19:14
 */

namespace common\modules\post\query;


use common\modules\langs\components\QueryBehavior;
use common\modules\post\models\Post;
use yii\db\ActiveQuery;

class PostQuery extends ActiveQuery
{
    public function behaviors()
    {
        return [
            'lang' => [
                'class' => QueryBehavior::className(),
                'alias' => Post::tableName()
            ],
        ];
    }

    public function active()
    {
        return $this->andWhere(['status' => Post::STATUS_ACTIVE])
            ->andWhere(['<', 'published_at', time()]);
    }

    public function slug($slug = null)
    {
        if ($slug == null) {
            return false;
        }
        $this->active();
        $this->lang();
        $this->andWhere(['slug' => $slug]);
        return $this;
    }


    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }

    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

}